# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-07-10 14:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='dci',
        ),
        migrations.DeleteModel(
            name='Location',
        ),
    ]
