# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2019-02-24 13:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Map', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='makaneyya',
            name='gbifQuery',
        ),
    ]
