# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2019-02-24 13:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Map', '0002_remove_makaneyya_gbifquery'),
    ]

    operations = [
        migrations.AddField(
            model_name='makaneyya',
            name='gbifQuery',
            field=models.CharField(default='', max_length=500),
        ),
    ]
