# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2019-03-18 14:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Map', '0004_makaneyya_gbifquerybyarea'),
    ]

    operations = [
        migrations.AddField(
            model_name='makaneyya',
            name='isGBIFMakanyyea',
            field=models.BooleanField(default=False),
        ),
    ]
