# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2019-05-19 12:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Map', '0005_makaneyya_isgbifmakanyyea'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataelement',
            name='ar_format',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='dataelement',
            name='ar_subject',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='dataelement',
            name='ar_title',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='dataelement',
            name='language',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='dataelement',
            name='subject',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='dataelement',
            name='title',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='makaneyya',
            name='description',
            field=models.TextField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='makaneyya',
            name='gbifQuery',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='makaneyya',
            name='gbifQueryByArea',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='makaneyya',
            name='lat',
            field=models.FloatField(blank=True, default=35.239109, null=True, verbose_name='latitude'),
        ),
        migrations.AlterField(
            model_name='makaneyya',
            name='lon',
            field=models.FloatField(blank=True, default=32.223516, null=True, verbose_name='longitude'),
        ),
    ]
