# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2019-05-21 11:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Map', '0010_dataelement_gbif_reference'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dataelement',
            name='gbif_reference',
        ),
    ]
