# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2019-05-21 11:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Map', '0012_dataelement_identifier'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dataelement',
            name='identifier',
        ),
    ]
