# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2019-05-21 11:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Map', '0013_remove_dataelement_identifier'),
    ]

    operations = [
        migrations.AddField(
            model_name='dataelement',
            name='identifier',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
