# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2019-07-29 13:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Map', '0016_auto_20190729_1250'),
    ]

    operations = [
        migrations.AlterField(
            model_name='makaneyya',
            name='gbifQuery',
            field=models.CharField(blank=True, default='', max_length=16000),
        ),
    ]
