# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2019-08-01 12:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Map', '0017_auto_20190729_1311'),
    ]

    operations = [
        migrations.AlterField(
            model_name='makaneyya',
            name='gbifQuery',
            field=models.CharField(blank=True, default='', max_length=100000),
        ),
    ]
